### ISSUE TITLE
Wrong result for q=[0.70710678, 0.70710678, 0.00000000, 0.00000000]

### ISSUE THREAD

**Issue by maxpla3** [evbernardes/quaternion_to_euler#1]
Calling
```
q = np.asarray([[0.70710678, 0.70710678, 0.00000000, 0.00000000]])
print(_compute_euler_from_quat(q, 'xyz', False))
```
results in
`[[ 3.14159265  0.         -1.57079633]]`
but the quaternion above simply describes a rotation around axis x with an angle of 90°. So the result should be:
`[[ 1.57079633  0.         0.]]`

**Comment by evbernardes** [comment]
@maxpla3 In this implementation, I am following the same convention as SciPy: the real part is the last element.
This means that a rotation around axis x of angle 90 degrees should be: 
```
q = np.asarray([[1/sqrt(2), 0, 0, 1/sqrt(2)]])
```
Instead of:
```
q = np.asarray([[1/sqrt(2), 1/sqrt(2), 0, 0]])
```

**Comment by maxpla3** [comment]
Thank you for the quick reply!

**Comment by evbernardes** [comment]
> Thank you for the quick reply!

You're welcome! If you're interested, this algorithm has been merged into Scipy and Sympy already.

The Sympy implementation is particularly interesting, since you can study it symbolically :)
